version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi
    external_links:
      - streamlit:streamlit
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    container_name: streamlit
    volumes:
      - ./frontend:/frontend
    command: streamlit run client.py
    ports:
      - "80:80"